# -*- eval: (add-hook 'after-save-hook (lambda nil (org-babel-tangle)) nil t); -*-
:PROPERTIES:
:ID:       C6F07644-D261-483C-8296-6EA8F133C481
:END:

#+TITLE: Emacs Literate Configuration
#+AUTHOR: Giles Paterson
#+PROPERTY: header-args :tangle yes

:PROPERTIES:
:VISIBILITY: children
:END:

* Table of Contexts :TOC_3_gh:
- [[#about-this-file][About this file]]
  - [[#tangle-on-save][Tangle on Save]]
  - [[#visibility-settings][Visibility Settings]]
  - [[#table-of-contents][Table of Contents]]
- [[#early-init][Early Init]]
  - [[#which-platform-is-this][Which platform is this?]]
  - [[#basic-frame-window-configuration][Basic frame (window) configuration]]
  - [[#disable-the-tool-bar-and-menu-bar][Disable the tool-bar and menu-bar]]
  - [[#set-the-frame-size][Set the frame size]]
  - [[#package-configuration][Package configuration]]
  - [[#tweak-startup-time-and-garbage-collection][Tweak startup time and garbage collection]]
- [[#general-emacs-settings][General Emacs Settings]]
  - [[#ensure-frame-gets-focus][Ensure frame gets focus]]
  - [[#use-package][Use-Package]]
  - [[#diminish][Diminish]]
  - [[#todo-garbage-collection-again][TODO: Garbage Collection (again)]]
  - [[#personal-information][Personal Information]]
  - [[#fix-defaults][Fix defaults]]
  - [[#automatically-revert-buffers][Automatically Revert Buffers]]
  - [[#tabs][Tabs]]
  - [[#disable-use-of-the-customize-file][Disable use of the customize file]]
  - [[#disable-backup-files][Disable backup files]]
  - [[#utf-8-all-the-things][UTF-8 all the things!]]
  - [[#unbind-the-pesky-sleep-key][Unbind the pesky sleep key]]
  - [[#switch-between-windows-easily][Switch between windows easily]]
  - [[#use-y-or-n-instead-of-yes-or-no][Use 'y' or 'n' instead of 'yes' or 'no']]
  - [[#fix-macos-path-nonsense][Fix MacOS Path nonsense]]
  - [[#a-function-to-set-the-framesize-for-streaming][A function to set the framesize for streaming]]
  - [[#enable-recentf-mode-recent-files][Enable recentf mode (recent-files)]]
  - [[#enable-overwriting-selected-text][Enable overwriting selected text]]
  - [[#show-trailing-white-space][Show trailing white space]]
  - [[#highlight-current-line][Highlight current line]]
  - [[#undo-tree][Undo Tree]]
  - [[#theme][Theme]]
    - [[#mode-line][Mode line]]
  - [[#fonts][Fonts]]
  - [[#which-key][Which key]]
  - [[#smart-move-to-beginning-of-line][Smart move to beginning of line]]
- [[#yasnippet---text-completion][YASnippet - text completion]]
- [[#org-mode][Org Mode]]
  - [[#toc-org][Toc-org]]
  - [[#org-capture][Org Capture]]
  - [[#org-protocol][Org Protocol]]
  - [[#org-ql][org-ql]]
  - [[#org-present][org-present]]
  - [[#org-exporters][Org Exporters]]
    - [[#markdown-github-flavoured][Markdown (Github Flavoured)]]
    - [[#typst][Typst]]
- [[#markdown][Markdown]]
- [[#completion-framework][Completion Framework]]
  - [[#ivy][Ivy]]
  - [[#counsel][Counsel]]
  - [[#ivy-rich][Ivy-Rich]]
  - [[#swiper][Swiper]]
- [[#git-stuff][Git stuff]]
- [[#projectile][Projectile]]
  - [[#counsel-projectile-org-capture][counsel-projectile-org-capture]]
- [[#codetext-completion-company-mode][Code/Text Completion (company-mode)]]
- [[#parentheses][Parentheses]]
- [[#line-numbers][Line numbers]]
- [[#development-languages][Development languages]]
  - [[#treemacs][Treemacs]]
  - [[#javascriptweb-development-lsp][Javascript/web development (lsp?)]]
  - [[#java][Java]]
    - [[#lsp-mode-deprecated][lsp-mode (Deprecated)]]
    - [[#eglot][eglot]]
    - [[#tree-sitter][tree-sitter]]
    - [[#cucumber-tests][Cucumber tests]]
  - [[#rust][Rust]]
- [[#yaml][Yaml]]
- [[#restclient][Restclient]]
- [[#ulisp][uLisp]]
- [[#remote-access-with-tramp][Remote access with Tramp]]
- [[#structurizr-mode][Structurizr Mode]]
- [[#sql-mode-disabled][SQL Mode (Disabled)]]
- [[#llm-assistant][LLM assistant]]
  - [[#local-llms-disabled][Local LLMs [Disabled]]]
  - [[#gptel-disabled][GPTEL [Disabled]]]
  - [[#editor-code-assistant][Editor Code Assistant]]
  - [[#mcp-usage-disabled][MCP usage [Disabled]]]
- [[#scheme][Scheme]]

* About this file
This configuration is inspired by [[https://github.com/vidjuheffex/dotemacs][vidjuheffex's config]] and [[https://github.com/gilbertw1/emacs-literate-starter][gilbertw1's config]]. I've also taken inspiration from https://blog.sumtypeofway.com/posts/emacs-config.html and https://assortedarray.com/posts/my-init-org-setup/.

This is a literate configuration, meaning that it's an org file with embedded code blocks that form the configuration for emacs. Having the code blocks in an org file allows me to document everything with the code it relates to.

** Tangle on Save
   Rather than using a stub init.el that calls =org-babel-load-file= on startup, I'm using a hook to tangle this file when I save. This means that I only have one configuration file, and hopefully startup will be quicker too.

   I'm using a file variable, added with =M-x add-file-local-variable-prop-line=, to set the eval hook in the first line of this file.

   #+begin_example emacs-lisp
     eval: (add-hook 'after-save-hook (lambda nil (org-babel-tangle)) nil t);
   #+end_example

   Alternatively, the file can be manually tangled with =M-x org-babel-tangle= or =C-c C-v t=.

** Visibility Settings
 Next we have a property defined on the [[Configuration][Configuration]] heading that defines the visibility that tells org to show it's direct children on startup. This way a clean outline of all sub headings under Configuration is shown each time this file is opened in org-mode.

** Table of Contents
 Finally, there is a [[Table of Contents][Table of Contents]] heading that includes the tag: =:TOC_3_gh:=. This tells an org-mode package =toc-org= to generate a table of contents under this heading that has a max depth of 3 and is created using Github-style hrefs. This table of contents is updated everytime the file is saved and makes for a functional table of contents that works properly directly on github.

* Early Init
  Emacs 27 introduced the =early-init.el= file that is loaded very early in the startup process. It's intended for customizing how the package system is initialized, so let's do our package config there:

  Any code in this section should not depend on a particular package or the emacs frame being in any given state. It's meant for doing initial basic configuration before the frame is created.

** Which platform is this?
:PROPERTIES:
:ID:       0D0A773D-A583-47FF-BFB9-EF57158C5B52
:END:
  This would be a good place to set any device or location specific flags. For example, if I need different config at home compared to work, then I could detect the location/machine here and set an appropriate variable to be used in the rest of the config.
#+begin_src emacs-listp :tangle early-init.el
  (defconst gp/env-macos (eq system-type 'darwin))
#+end_src

** Basic frame (window) configuration
:PROPERTIES:
:ID:       7F5A5E55-6114-4870-8641-9CB3581F910B
:END:
By doing basic frame config here, then it will apply to the initial frame and all subsequent frames.

Allow setting frame size by pixels, and also prevent emacs from resizing the frame when we change font sizes.
#+begin_src emacs-lisp :tangle early-init.el
  (setq frame-resize-pixelwise t) ;; use pixels to specify frame size
  (setq frame-inhibit-implied-resize 'force) ;; don't resize frame if font size changes
  (setq frame-title-format '("%b")) ;; current buffer name
  (setq ring-bell-function 'ignore) ;; use visual instead of audible bell
  (setq visible-bell t)
  (setq inhibit-splash-screen t)
  (setq inhibit-startup-screen t)      ;; No need for a startup screen
  (setq initial-scratch-message nil)   ;; or to tell me what the scratch buffer is
  (setq inhibit-startup-echo-area-message user-login-name)
  (setq inhibit-startup-message t)
#+end_src

** Disable the tool-bar and menu-bar
:PROPERTIES:
:ID:       D154C28B-EF1E-4256-A21D-76F5E1E03D82
:END:
 #+begin_src emacs-lisp :tangle early-init.el
   (tool-bar-mode -1)
   (menu-bar-mode -1)
 #+end_src

** Set the frame size
:PROPERTIES:
:ID:       764CF0CF-BD76-48B4-9D25-7BC7E4F10396
:END:
An emacs Frame is what most would call a window; Emacs predates commonly accepted GUI terms.

#+begin_src emacs-lisp :tangle early-init.el
  (dolist (variable '(initial-frame-alist default-frame-alist))
    (set variable `((width . (text-pixels . 1000))
                    (height . (text-pixels . 700)))))
#+end_src

** Package configuration
:PROPERTIES:
:ID:       7580879F-A933-4B89-8C98-5CA398307E74
:END:
  #+begin_src emacs-lisp :tangle early-init.el
    ;;; early-init.el -*- lexical-binding: t; eval: (view-mode -1); -*-
    (require 'package)
    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
    (add-to-list 'package-archives '("nongnu" . "https://elpa.nongnu.org/nongnu/") t)
    (add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)

    (setq package-enable-at-startup t) ;; enable package cache to initialise installed packages
    (setq package-install-upgrade-built-in t) ;; enable upgrading of built in packages
  #+end_src

** Tweak startup time and garbage collection
:PROPERTIES:
:ID:       CDA6A6BB-CC8D-4FEC-8072-6FF447298392
:END:
  Taking inspiration from [[https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org#how-does-doom-start-up-so-quickly][doom-emacs]], I'm going to bump the garbage collection threshold up during startup to help speed things up. Then we reset it after startup.
   #+begin_src emacs-lisp :tangle early-init.el
     ;; (defvar gp/gc-cons-threshold 16777216) ;; 16mb
     (defvar gp/gc-cons-threshold (* 100 100 8))
     (defvar gp/file-name-handler-alist file-name-handler-alist)
     (defvar gp/vc-handled-backends vc-handled-backends)

     ;; set initial values high to speed up startup
     (setq gc-cons-threshold most-positive-fixnum
           gc-cons-percentage 0.6)

     (setq file-name-handler-alist nil
           vc-handled-backends nil)

     ;; ensure normal values are set after startup
     (add-hook 'emacs-startup-hook
               (lambda ()
                 (setq gc-cons-threshold gp/gc-cons-threshold
                       gc-cons-percentage 0.1
                       file-name-handler-alist gp/file-name-handler-alist
                       vc-handled-backends gp/vc-handled-backends)))

   #+end_src

* General Emacs Settings
:PROPERTIES:
:ID:       473B06A5-3265-44C2-A20F-977D6586B83A
:END:
  Make elisp in this file have proper scoping. [[https://www.emacswiki.org/emacs/DynamicBindingVsLexicalBinding][This Emacswiki article explains it well.]]

  I also enable =view-mode=, to make the tangled file read-only, as a reminder that it is auto-generated and shouldn't be manually edited.

#+begin_src emacs-lisp :comments no
;;; init.el -*- lexical-binding: t ; eval: (view-mode -1); -*-
#+end_src

** Ensure frame gets focus
:PROPERTIES:
:ID:       2A399876-545C-4C6E-BEDE-7AF7384169EF
:END:
On MacOS, the initial emacs frame doesn't get focus automatically, meaning it appears behind the terminal window I've just launched it from. This should sort that.

#+begin_src emacs-lisp
  (if gp/env-macos
      (select-frame-set-input-focus (selected-frame)))
#+end_src


** Use-Package
:PROPERTIES:
:ID:       006729B7-D364-4839-9530-DA5CACCE4FD2
:END:
   I like to use [[https://github.com/jwiegley/use-package][use-package]] to keep things tidy and speedy on startup, so this makes sure it's available. I set it to defer loading packages unless told otherwise, this speeds up initialisation.

 #+begin_src emacs-lisp
   (when (< emacs-major-version 29)
     (unless (package-installed-p 'use-package)
       (unless package-archive-contents
         (package-refresh-contents))
       (package-install 'use-package)))

   (setq use-package-always-ensure t
         use-package-ensure-all t
         use-package-always-defer t)
   (require 'use-package)
   (require 'use-package-ensure)
 #+end_src

 Hide package installation warnings, since they're usually not important.
 #+begin_src emacs-lisp
   ;; hide package installation warnings
   (add-to-list 'display-buffer-alist
                '("\\`\\*\\(Warnings\\|Compile-Log\\)\\*\\'"
                  (display-buffer-no-window)
                  (allow-no-window . t)))
 #+end_src

   I like to make sure all my packages are up to date, so I use auto-package-update.
   #+begin_src emacs-lisp
     (use-package auto-package-update
       :custom
       (auto-package-update-delete-old-versions t)
       :init
       (auto-package-update-maybe))
 #+end_src
** Diminish
:PROPERTIES:
:ID:       95B1E0FD-5FA3-4AE5-9C46-583367863634
:END:
Use diminish so that use-package can hide modes from the mode line when we ask it to.
#+begin_src emacs-lisp
(use-package diminish)
#+end_src

** TODO: Garbage Collection (again)
:PROPERTIES:
:ID:       91664649-6977-41AB-A14B-603EAE8D67F9
:END:
   Increase the garbage collection thresholds when using the minibuffer, and return to normal afterwards.

 #+begin_src emacs-lisp
   ;; ;; max memory available for gc when opening minibuffer
   ;; (defun gp/defer-garbage-collection-h ()
   ;;   (setq gc-cons-threshold most-positive-fixnum))

   ;; (defun gp/restore-garbage-collection-h ()
   ;;   ;; Defer it so that commands launched immediately after will enjoy the
   ;;   ;; benefits.
   ;;   (run-at-time
   ;;    1 nil (lambda () (setq gc-cons-threshold gp/gc-cons-threshold))))

   ;; (add-hook 'minibuffer-setup-hook #'gp/defer-garbage-collection-h)
   ;; (add-hook 'minibuffer-exit-hook #'gp/restore-garbage-collection-h)
 #+end_src
** Personal Information
:PROPERTIES:
:ID:       E1B3BA7A-05F4-4584-AD69-CC654D962FCA
:END:
    This is me
 #+begin_src emacs-lisp
 (setq user-full-name "Giles Paterson"
       user-mail-address "giles@vurt.uk")
 #+end_src

** Fix defaults
:PROPERTIES:
:ID:       BCE8E65B-BF24-48DC-BAFE-2F8C2C7BB509
:END:
 Reset some emacs defaults that date from prehistoric times

 #+begin_src emacs-lisp
   (setq sentence-end-double-space nil) ;; Who the hell does this in 2021?
   (setq kill-whole-line t)             ;; Let C-k delete the whole line.
   (setq native-comp-async-report-warnings-errors nil) ;; don't show native complilation warnings
 #+end_src

** Automatically Revert Buffers
:PROPERTIES:
:ID:       6A392A9B-30D0-439A-B155-C20634A22E85
:END:
   If a file changes on disk, I want the buffer to update. Emacs will prompt if I have unsaved changes, so this is safe to do.
   #+begin_src emacs-lisp
     (global-auto-revert-mode 1)
   #+end_src
** Tabs
:PROPERTIES:
:ID:       08D364F8-123A-4BB1-9913-C105C28EEC63
:END:
    Tabs, spaces. It's a whole thing. Fundamentally, I'd love for tabs to work like tabs, and allow users to set their own tab spacing, but that's not the world we live in anymore. So, I need to use spaces.
    #+begin_src emacs-lisp
      (setq-default indent-tabs-mode nil)
      (setq tab-width 4)
    #+end_src
** Disable use of the customize file
:PROPERTIES:
:ID:       F07D6EEA-5A89-4D57-A12F-B8B2F605B07A
:END:
    I find this annoying, as it's all too easy to override something by accident with the customize functionality, then your emacs init doesn't work. You can't get rid of it completely, but you can point it at another file, to avoid cluttering up init.el

#+begin_src emacs-lisp
  (setq custom-file "~/.emacs.d/custom.el")
  (when (file-exists-p custom-file)
    (load custom-file))
  (setq custom-safe-themes t)
#+end_src

** Disable backup files
:PROPERTIES:
:ID:       4F01692E-6213-4FB3-A196-E4C31A2EC97B
:END:
    I've never found emacs backup files to be particularly useful
#+begin_src emacs-lisp
  (setq make-backup-files nil)
  (setq auto-save-default nil)
  (setq create-lockfiles nil)
#+end_src

** UTF-8 all the things!
:PROPERTIES:
:ID:       1169D0C8-8481-407E-AED1-A19A4CD86E59
:END:
    utf-8 should be the default for everything.

#+begin_src emacs-lisp
  (set-charset-priority 'unicode)
  (setq locale-coding-system 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-selection-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)
  (setq default-process-coding-system '(utf-8-unix . utf-8-unix))
#+end_src

** Unbind the pesky sleep key
:PROPERTIES:
:ID:       1D92A60E-E6A8-4D57-8CD2-594E6FD5EF84
:END:
#+begin_src emacs-lisp
  (global-unset-key [(control z)])
  (global-unset-key [(control x)(control z)])
#+end_src

** Switch between windows easily
:PROPERTIES:
:ID:       CCC9609B-E261-4AF5-8139-26F3FD13E52D
:END:
switch-window enables selecting windows by number (or letter). You can jump directly to a window rather than cycling through them or navigating up/down/left/right with windmove-*

#+begin_src emacs-lisp
  (use-package switch-window
    :bind (("C-x o" . switch-window)
           ("C-x 1" . switch-window-then-maximize)
           ("C-x 2" . switch-window-then-split-below)
           ("C-x 3" . switch-window-then-split-right)
           ("C-x 0" . switch-window-then-delete)))
#+end_src

When there are more than two windows present, it will overlay the window with a number so you can jump directly to it. A similar process is enabled when splitting.

** Use 'y' or 'n' instead of 'yes' or 'no'
:PROPERTIES:
:ID:       A11F5330-9553-429C-ACAB-2BD88964C449
:END:
#+begin_src emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+end_src

** Fix MacOS Path nonsense
:PROPERTIES:
:ID:       34A1F6CD-CD08-4ACF-8ADE-EF01EBA6ADAF
:END:
   on OS X, where an Emacs instance launched as a GUI app inherits a default minimal set of environment variables that
   are probably not the ones you see in a terminal window. Similarly, if you start Emacs as a daemon from systemd or
   launchd, it will run with a default set of environment variables.

This library solves this problem by copying important environment variables from the user's shell: it works by asking your shell to print out the variables of interest, then copying them into the Emacs environment.

#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :ensure t)
  ;;Later on, after loading exec-path-from-shell package

  (if gp/env-macos
     (add-hook 'after-init-hook 'exec-path-from-shell-initialize))
#+end_src

** A function to set the framesize for streaming
:PROPERTIES:
:ID:       A2272849-527C-4D8B-809E-67C61FAE9726
:END:
 Sometimes I want to show emacs via OBS Studio, which I have set to 1280x720p. A frame size of 109x31 fits perfectly for me. Here's a function I can call to switch to toggle between that frame size and my normal one, when I need it.
 #+begin_src emacs-lisp
   (defvar gp/frame-normal-width 110)
   (defvar gp/frame-normal-height 58)
   (defvar gp/frame-streaming-width-720 109)
   (defvar gp/frame-streaming-height-720 31)
   (defvar gp/frame-streaming-width-1080 188)
   (defvar gp/frame-streaming-height-1080 48)
   (defvar gp/is-streaming-size nil)

   (defun gp/frame-size-streaming-720 ()
     "Sets the frame size so it's suitable for streaming via OBS at 720p"
     (interactive)
     (set-frame-width (selected-frame) gp/frame-streaming-width-720)
     (set-frame-height (selected-frame) gp/frame-streaming-height-720)
     (setq gp/is-streaming-size t))

   (defun gp/frame-size-streaming-1080 ()
     "Sets the frame size so it's suitable for streaming via OBS at 1080p"
     (interactive)
     (set-frame-width (selected-frame) gp/frame-streaming-width-1080)
     (set-frame-height (selected-frame) gp/frame-streaming-height-1080)
     (setq gp/is-streaming-size t))

   (defun gp/frame-size-normal ()
     "Sets the frame size to my default values"
     (interactive)
     (set-frame-width (selected-frame) gp/frame-normal-width)
     (set-frame-height (selected-frame) gp/frame-normal-height)
     (setq gp/is-streaming-size nil))

   (defun gp/streaming-toggle ()
     "Toggles between streaming and normal frame sizes"
     (interactive)
     (if (eq gp/is-streaming-size nil)
       (gp/frame-size-streaming-720)
     ; else
     (gp/frame-size-normal)))

   ;; (gp/frame-size-normal)
 #+end_src

** Enable recentf mode ([[https://www.emacswiki.org/emacs/RecentFiles][recent-files]])
:PROPERTIES:
:ID:       B48710C7-03D4-4F42-8D7A-BE8F115471EB
:END:
Recentf is useful to re-open a file you worked on recently, but it's good to set some limits on it. Also, ignore any package files from elpa, as they make it less than useful.
#+begin_src emacs-lisp
  (require 'recentf)
  (recentf-mode 1)
  (setq recentf-max-menu-items 50)
  (setq recentf-max-saved-items 250)
  ;; (global-set-key "\C-x\ \C-r" 'recentf-open-files)
  (add-to-list 'recentf-exclude "\\elpa")
#+end_src

I've replaced the recentf-open-files keybinding with counsel-recentf instead.

** Enable overwriting selected text
:PROPERTIES:
:ID:       E4FC48D6-8A3A-49BA-B76A-36ABF3B4672C
:END:
#+begin_src emacs-lisp
  ;; Delete the selected text upon text insertion
  (use-package delsel
    :ensure nil ; no need to install it as it is built-in
    :hook (after-init . delete-selection-mode))
#+end_src


** Show trailing white space
:PROPERTIES:
:ID:       1339F932-CB64-4CC3-B1F2-A38F14B933A7
:END:
   Show white space at the ends of line, to avoid embarassment when comitting something. Then delete them with M-x delete-trailing-whitespace
  #+begin_src emacs-lisp
    (setq-default show-trailing-whitespace t)
  #+end_src

   actually, just delete them automatically when we save.
  #+begin_src emacs-lisp
    (add-hook 'before-save-hook #'delete-trailing-whitespace)
  #+end_src

  We don't want whitespace to be highlighted in all modes, notably the minibuffer, term and compilation buffers. So let's disable it for those modes
  #+begin_src emacs-lisp
    (dolist (hook '(special-mode-hook
                    term-mode-hook
                    comint-mode-hook
                    compilation-mode-hook
                    minibuffer-setup-hook))
      (add-hook hook
                (lambda () (setq show-trailing-whitespace nil))))
  #+end_src

** Highlight current line
:PROPERTIES:
:ID:       6DB8BDB6-EFB7-4979-A018-E97E7636E766
:END:
This is useful in many situations, so enable it for programming and
text editing based modes.
#+begin_src emacs-lisp
  (require 'hl-line)
  (add-hook 'prog-mode-hook #'hl-line-mode)
  (add-hook 'text-mode-hook #'hl-line-mode)
#+end_src

** Undo Tree
:PROPERTIES:
:ID:       058ED1B6-8F38-4973-B037-19BFD6727D01
:END:
Emacs has a powerful, but confusing, undo model. Undo tree makes it easier to use and lets you get back pretty much anything you've done.
#+begin_src emacs-lisp
(use-package undo-tree
  :diminish
  :bind (("C-c _" . undo-tree-visualize))
  :config
  (global-undo-tree-mode +1)
  (unbind-key "M-_" undo-tree-map))
#+end_src

** Theme
:PROPERTIES:
:ID:       9C106513-D6EB-4CA1-AA52-4428928DEB32
:END:
I like a dark editor, and base16-brewer is what I've got used previously. But now I'm trying modus-vivendi. Previously I used vscode-dark-plus but that doesn't work in emacs 30.
#+begin_src emacs-lisp
  (load-theme 'modus-vivendi t)
  ;; (use-package vscode-dark-plus-theme
  ;;   :ensure t
  ;;   :config
  ;;   (load-theme 'vscode-dark-plus t))
  ;; ;; (add-to-list 'custom-theme-load-path (concat user-emacs-directory "themes"))
  ;; (load-theme 'vscode-dark-plus t)
  ;; ;; Remove the border around the TODO word on org-mode files
  ;; (setq vscode-dark-plus-box-org-todo nil)

  ;; ;; Do not set different heights for some org faces
  ;; (setq vscode-dark-plus-scale-org-faces nil)
#+end_src

*** Mode line
:PROPERTIES:
:ID:       441F3154-A8F7-44CF-B45E-8541749BAC98
:END:
    I'm using doom-modeline as it looks nice and is pretty customisable. +It depends on =all-the-icons= so you need to run =M-x all-the-icons-install-fonts= to make sure the fonts are installed.+

    Now it seems to depend on ~nerd-icons~ so you need to run ~M-x nerd-icons-install-fonts~ instead.
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :custom
    (column-number-mode t)
    (doom-modeline-project-detection 'project)
    :init (doom-modeline-mode 1))
#+end_src

** Fonts
:PROPERTIES:
:ID:       A5078723-93E9-4922-810C-0735F0F56D47
:END:
A matter of personal opinion, but a modern mono-spaced font makes emacs look a lot better.

I'm setting Roboto Light for the variable pitch font and Fira Code for fixed-pitch (i.e. monospace)

#+begin_src emacs-lisp
  ;; (defvar gp/fixed-width-font "Cascadia Code 14")
  (defvar gp/fixed-width-font "Fira Code")
  (defvar gp/fixed-width-weight 'medium)
  (defvar gp/fixed-width-height 140) ;; 1/10ths of pt (i.e. 14pt)
  (defvar gp/variable-width-font "Roboto")

  (set-face-attribute 'default nil :font gp/fixed-width-font :weight gp/fixed-width-weight :height gp/fixed-width-height)
  (set-face-attribute 'fixed-pitch nil :font gp/fixed-width-font :weight gp/fixed-width-weight :height gp/fixed-width-height)
  (set-face-attribute 'variable-pitch nil :font gp/variable-width-font :weight 'light :height 170)

  (dolist (face '(default fixed-pitch))
    (set-face-attribute `,face nil :font gp/fixed-width-font))

  ;;(add-to-list 'default-frame-alist '(font . "Roboto Mono Light 14"))
  ;;(set-fontset-font "fontset-default"  '(#x2600 . #x26ff) "Fira Code 16")
  (setq-default line-spacing 0)
  (setq x-underline-at-descent-line t)
#+end_src

** Which key
:PROPERTIES:
:ID:       A551587C-D53A-4827-A596-126AA15B5322
:END:
   [[https://github.com/justbur/emacs-which-key][Which-key]] enables discoverability of available commands.

   If you ever want to just explore the available keybindings, then try =M-x which-key-show-top-level= or =M-x which-key-show-major-mode=

#+begin_src emacs-lisp
  (use-package which-key
    :diminish
    :demand t
    :config
    (which-key-mode 1)
    (which-key-setup-side-window-bottom))
#+end_src

** Smart move to beginning of line
:PROPERTIES:
:ID:       BAEC7CD6-6E1A-400A-A2A6-7DDD8C089857
:END:
This function was originally taken from the [[https://emacsredux.com/blog/2013/05/22/smarter-navigation-to-the-beginning-of-a-line/][Emacs Redux]] blog. It means that pressing C-a will move the cursor to the start of the text on a line. Pressing it again will jump to the physical start of the line.

#+begin_src emacs-lisp
  (defun gp/smarter-move-beginning-of-line (arg)
  "Move point back to indentation of beginning of line.

Move point to the first non-whitespace character on this line.
If point is already there, move to the beginning of the line.
Effectively toggle between the first non-whitespace character and
the beginning of the line.

If ARG is not nil or 1, move forward ARG - 1 lines first.  If
point reaches the beginning or end of the buffer, stop there."
  (interactive "^p")
  (setq arg (or arg 1))

  ;; Move lines first
  (when (/= arg 1)
    (let ((line-move-visual nil))
      (forward-line (1- arg))))

  (let ((orig-point (point)))
    (back-to-indentation)
    (when (= orig-point (point))
      (move-beginning-of-line 1))))

;; remap C-a to `smarter-move-beginning-of-line'
(global-set-key [remap move-beginning-of-line]
                'gp/smarter-move-beginning-of-line)
#+end_src

* YASnippet - text completion

#+begin_src emacs-lisp :tangle no
(use-package yasnippet
       :ensure t
       :init
       (yas-global-mode 1)
       :config
       (add-to-list 'yas-snippet-dirs (locate-user-emacs-file "snippets")))
#+end_src

* Org Mode
:PROPERTIES:
:ID:       66E848BA-D50A-427B-8660-1FCAD5A8FF8B
:END:

#+begin_src emacs-lisp
  (use-package org
    ;; :defer t
    :hook ((org-mode . visual-line-mode)
           (org-mode . variable-pitch-mode)
           (org-babel-after-execute . org-display-inline-images))
    :mode (("\\.org$" . org-mode))
    :bind (("C-c l" . org-store-link)) ;;store link to current org section
    :init
    (defun gp/list-note-files ()
      "Get list of org files in my notes directory"
      (directory-files-recursively "~/Documents/syncthing/org/notes/" "\\`[^.].*\\.org\\'"))

    (defun gp/org-backlinks ()
      "Search for backlinks to current entry."
      (interactive)
        (let ((link (condition-case nil
                        (org-id-store-link)
                      (error "Unable to create a link to here"))))
          (org-occur-in-agenda-files (regexp-quote link))))

    ;; function to provide id: link compeltion based on my org files.
    (defun gp/org-id-complete-link (&optional arg)
      "Create an id: ink using completion."
      (concat "id:" (org-id-get-with-outline-path-completion org-refile-targets)))

    :custom

    (org-startup-with-inline-images t)
    (org-src-tab-acts-natively t)
    (org-src-fontify-natively t) ;; native src block fontification
    (org-src-window-setup 'current-window) ;; edit src blocks in place, rather than a new window
    (org-hide-emphasis-markers t) ;;actually emphasise text (e.g. show as italic instead of /italic/)
    (org-confirm-babel-evaluate nil)
    (org-indent-indentation-per-level 2)
    (org-adapt-indentation nil)
    ;; Make note files searchable without just adding them to agenda files, and slowing everything down.
    (org-agenda-text-search-extra-files (gp/list-note-files))
    (org-refile-targets '((nil :maxlevel . 9)
                          (org-agenda-files :maxlevel . 9)
                          (gp/list-note-files :maxlevel . 2)))

    (org-outline-path-complete-in-steps nil)         ; Refile in a single go
    (org-refile-use-outline-path t)                  ; Show full paths for refiling
    ;; use uuid for links
    (org-id-link-to-org-use-id t)
    (org-id-extra-files 'org-agenda-text-search-extra-files)

    ;; automatically indent headings and paragraphs
    (org-startup-indented t)

    (org-export-with-broken-links 'mark) ;;mark broken links in exported output
    :config
    ;; load more languages for org-babel
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (shell      . t)
       (sql        . t)))


    ;; This config sets my completion function to be called when inserting id: links
    (org-link-set-parameters "id"
                             :complete 'gp/org-id-complete-link)

    ;; In order for variable-pitch-mode to work properly, I need to set fixed pitch fonts for various org faces:
    (custom-theme-set-faces
     'user
     '(org-block ((t (:inherit fixed-pitch))))
     '(org-checkbox ((t (:inherit fixed-pitch))))
     '(org-code ((t (:inherit (shadow fixed-pitch)))))
     '(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
     '(org-formula ((t (:inherit (fixed-pitch)))))
     '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch)))))
     '(org-property-value ((t (:inherit fixed-pitch))) t)
     '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
     '(org-table ((t (:inherit fixed-pitch))))
     '(org-tag ((t (:inherit (shadow fixed-pitch) :weight bold :height 0.8))))
     '(org-verbatim ((t (:inherit (shadow fixed-pitch)))))
     '(nxml-text ((t (:inherit (fixed-pitch))))))
    ;; (org-id-update-id-locations) ;; This line breaks org mode in emacs 30!
    )
#+end_src

Let's make org-mode have dyanmic wrapping, and center it in the frame so that it works a bit more like a typical word processor.

For this, I make use of [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] , then text behaves as if you'd used M-q but without actually adding line breaks to the source text.

#+begin_src emacs-lisp
  (use-package visual-fill-column
    :diminish
    :hook (org-mode . visual-fill-column-mode)
    :custom
    (visual-fill-column-width 120)
    (visual-fill-column-center-text t))
#+end_src

Previously I used  [[https://github.com/rnkn/olivetti][olivetti mode]] instead, but this should be a lighter weight approach.

#+begin_src emacs-lisp :tangle no
  (use-package olivetti
    :diminish
    :init
    (setq-default fill-column 120)
    :config
    (olivetti-set-width 100) ;; olivetti mode seems to go wider then 100, so I set the fill column to 120 to visually match.
    (setq olivetti-style "fancy")
    :hook (org-mode . olivetti-mode))
#+end_src

To make org mode look a bit nicer, I like to use the org-bullets package to replace headline markers with Unicode bullets.
#+begin_src emacs-lisp
  (use-package org-bullets
    :diminish
    :hook (org-mode . org-bullets-mode))
#+end_src


** Toc-org
:PROPERTIES:
:ID:       645D194F-01A8-4A97-97C0-FAF5403AC805
:END:
 Install the =toc-org= package after org mode is loaded. This enables automatic generation of up to
 date tables of contents.

 #+begin_src emacs-lisp
   (use-package toc-org
     :diminish
     :ensure t
     :after org
     :hook (org-mode . toc-org-mode))

 #+end_src
** Org Capture
:PROPERTIES:
:ID:       0B1D3C79-1E20-4F1C-907C-C86327A1C325
:END:
I'm trying to use org mode for managing a simple(ish) todo list. I want to be able to capture tasks quickly, then sort & action them appropriately.

I'll start with a single todo file and see how i get on with that.

I've also created a template for notes - it uses a function to create a new note file and then captures to that.
   #+begin_src emacs-lisp
     (use-package org-capture
       :ensure nil
       :after org-agenda
       :defer 1
       :bind (("C-c c" . org-capture))
       :config
       ;; set task priority range from A to C with default B
       (setq org-highest-priority ?A)
       (setq org-lowest-priority ?C)
       (setq org-default-priority ?B)

       ;; define todo states
       (setq org-todo-keywords
             '((sequence "TODO(t)" "WORK(w)" "DONE(d)")))

       ;; After a successful capture, update the org agenda extra files so that searching includes the newly captured file
       (defun gp/update-agenda-files ()
         (if org-note-abort
             ()
           (setq org-agenda-text-search-extra-files (gp/list-note-files))))

       (add-hook 'org-capture-after-finalize-hook 'gp/update-agenda-files)

       (defun gp/capture-note-file (path)
         "Create an org file in path"
         (let ((name (read-string "Name: ")))
           (expand-file-name (format "%s.org"
                                     name)
                             path)))

       (setq org-capture-templates
             '(
               ("t"    ; key
                "Todo" ; description
                entry  ; type
                (file+headline "~/Documents/syncthing/org/todo.org" "Tasks") ; target
                "* TODO [#B] %?" ;template
                )
               ("n"    ; key
                "Note" ; description
                entry  ; type
                (file (lambda () (gp/capture-note-file "~/Documents/syncthing/org/notes"))) ; target
                "* %? %(org-set-tags-command) \n%U" ; template
                )
               ("m"    ; key
                "Meeting" ; description
                entry  ; type
                (file (lambda () (gp/capture-note-file "~/Documents/syncthing/org/notes/meetings"))) ; target
                "* %? :meeting: \n%U" ; template
                :empty-lines 1
                )))
       )
   #+end_src

   #+RESULTS:
   : org-capture

   I start by defining C-c c as the keybinding to trigger capture. This is set globally so I can capture a note from anywhere in emacs.

#+begin_src emacs-lisp
  (use-package org-agenda
    :ensure nil
    :after org
    :bind (("C-c a" . org-agenda))
    :custom
    ;; open agenda in current window
    (org-agenda-window-setup (quote current-window))
    ;; file to save todo items
    ;(org-agenda-files (quote ("~/Documents/syncthing/org/todo.org")))
    (org-agenda-files '("~/Documents/syncthing/org"))
    (org-agenda-custom-commands
     '(("n" . "Search in notes")
       ("nt" "Note tags search" tags ""
        ((org-agenda-files (gp/list-note-files))))
       ("ns" "Note full test search" search ""
        ((org-agenda-files (gp/list-note-files))))))
    :config
    (add-to-list 'org-agenda-text-search-extra-files '(org-agenda-files :maxlevel . 2))
    )
#+end_src
** Org Protocol
:PROPERTIES:
:ID:       5B9A4096-C3CC-4A1A-B156-365171CAD243
:END:
   Org capture works well within emacs but if you want to make a note based on something in another application [[https://orgmode.org/manual/Protocols.html#Protocols][org-protocol]] can help.

   Firstly, we need to have the emacs server running, so emacsclient can talk to it.
   #+begin_src emacs-lisp
     (require 'server)
     (unless (server-running-p)
       (server-start))
   #+end_src

   Then we require org-protocol
   #+begin_src emacs-lisp
     (require 'org-protocol)
   #+end_src

   And that should be that. The host operating system needs to have a url handler registered for the org-protocol: url. For Mac OS, I've followed [[https://orgmode.org/manual/Protocols.html#Protocols][this approach using an apple script]].

   The "Web clip" capture template defined above can be used with this javascript bookmarklet to make a note using a selection from a web site.

   #+begin_src javascript :tangle no
     javascript:location.href='org-protocol://capture?template=w'+
      '&url='+encodeURIComponent(window.location.href)+
      '&title='+encodeURIComponent(document.title)+
      '&body='+encodeURIComponent(window.getSelection());
   #+end_src
** org-ql
:PROPERTIES:
:ID:       0FA9F9A3-D381-4C8C-AB93-E2FBA1313BB2
:END:
I'm going to try using org-ql and dynamic blocks to provide backlinks in my org notes. This is the approach I describe in my note taking notes (searching_notes.org)

I can insert a dynamic block with C-c C-x x and select "backlinks" from the list. This will add the block and update it, so any links to the current org section will be listed.

#+begin_src emacs-lisp

  (use-package org-ql
    :after org
    :bind ("C-c s" . gp/org-ql-search)
    :init
    (defun org-dblock-write:zorg-backlinks (&rest params)
      (let ((elements (org-ql-query
                       :from org-agenda-text-search-extra-files
                       :where `(link :target ,(org-id-store-link)))))
        (insert "Backlinks:\n")
        (dolist (element elements)
          (insert "- " (org-make-link-string (concat "id:" (org-element-property :ID element))
                                             (org-element-property :raw-value element))
                  "\n"))
        (delete-char -1)))

    ;; Enable inserting the dynamic block with C-x C-x x
    (defun org-insert-dblock:backlinks ()
      "Insert a dynamic block backlinks at point."
      (interactive)
      (atomic-change-group
        (org-create-dblock (list :name "zorg-backlinks")))
      (org-update-dblock))

    (org-dynamic-block-define "backlinks" #'org-insert-dblock:backlinks)
    ;; update dynamic blocks when saving
    ;; to ensure backlinks are always up to date.
    (add-hook 'before-save-hook #'org-update-all-dblocks)

    :config
    ;; search my notes with org-ql
    (defun gp/org-ql-search (query)
      "Search `org-agenda-text-search-extra-files' with `org-ql-search'."
      (interactive (list (read-string "Query: " )))
      (org-ql-search org-agenda-text-search-extra-files query :sort '(date) :super-groups nil :narrow narrow))
    )
#+end_src
** org-present
:PROPERTIES:
:ID:       4EB74E01-7A79-4A77-B486-3AA5BFBE02ED
:END:

For giving presentations with org mode. This is all taken from the System Crafters guide: https://systemcrafters.net/emacs-tips/presentations-with-org-present/

#+begin_src emacs-lisp
  (use-package org-present
    :init
    (defun gp/org-present-prepare-slide (buffer-name heading)
      ;; Show only top-level headlines
      (org-overview)

      ;; Unfold the current entry
      (org-show-entry)

      ;; Show only direct sub headings of the slide but don't expand them
      (org-show-children))

    (defun gp/org-present-start ()
      ;; Tweak font sizes
      (setq-local face-remapping-alist '((default (:height 1.5) variable-pitch)
                                         (header-line (:height 4.0) variable-pitch)
                                         (org-document-title (:height 1.75) org-document-title)
                                         (org-code (:height 1.55) org-code)
                                         (org-verbatim (:height 1.55) org-verbatim)
                                         (org-block (:height 1.25) org-block)
                                         (org-block-begin-line (:height 0.7) org-block)))

      ;; Set a blank header line string to create blank space at the top
      (setq header-line-format " ")

      ;; disable highlighting the current line
      (hl-line-mode -1)

      ;; hide the cursor
      ;;(org-present-hide-cursor)
      (setq-local cursor-type nil)

      ;; read only mode
      (org-present-read-only))

    (defun gp/org-present-end ()
      ;; Reset font customizations
      (setq-local face-remapping-alist '((default variable-pitch default)))

      ;; Clear the header line string so that it isn't displayed
      (setq header-line-format nil)

      ;; enable highlighting the current line
      (hl-line-mode)

      ;; show the cursor again
      ;;(org-present-show-cursor)
      (setq-local cursor-type 'box)

      ;; read write mode
      (org-present-read-write))

    :hook ((org-present-mode . gp/org-present-start)
           (org-present-mode-quit . gp/org-present-end)
           (org-present-after-navigate-functions . gp/org-present-prepare-slide))
    )
#+end_src
** Org Exporters
*** Markdown (Github Flavoured)
:PROPERTIES:
:ID:       051A0301-7836-4556-95EB-F716269BBFF0
:END:

#+begin_src emacs-lisp
  (use-package ox-gfm
    :defer 3
    :after org)
#+end_src
*** Typst
:PROPERTIES:
:ID:       6F0503B7-0384-4FC4-ADB4-299AA3BA4BCA
:END:

#+begin_src emacs-lisp
  (use-package ox-typst
    :defer 3
    :after org)
#+end_src
* Markdown
:PROPERTIES:
:ID:       DC424A68-5BB4-4BEC-8E6E-9EAD1BEC3A63
:END:
Sometimes I need to edit markdown, so here's how to configure [[https://github.com/jrblevin/markdown-mode][markdown-mode]].
For README.md files, use github flavoured markdown, otherwise use normal markdown mode.

#+begin_src emacs-lisp
  (use-package markdown-mode
    :mode (("README\\.md\\'" . gfm-mode)
           ("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode)))
#+end_src

* Completion Framework

** Ivy
:PROPERTIES:
:ID:       1783D2BA-EA97-4341-BBE4-23A583E92542
:END:
   I'm going to give Ivy a go (along with Swiper/Counsel) to see if I like it, instead of Helm.

 #+begin_src emacs-lisp
   (use-package ivy
     :diminish ivy-mode
     :custom
     (ivy-height 30)
     (ivy-use-virtual-buffers t)
     (ivy-use-selectable-prompt t)
     (ivy-count-format "(%d/%d) ")
     :config
     (ivy-mode 1))
 #+end_src

  I'll start with a minimal config - just setting the options recommended in the getting started section of the documentation.

** Counsel
:PROPERTIES:
:ID:       02D73BB3-8E7A-4E39-9C85-B8424401AEA7
:END:
   Similarly, for Counsel, I'll just enable counsel-mode to default to using counsel.
#+begin_src emacs-lisp
  (use-package counsel
    :diminish counsel-mode
    :bind (("C-x C-r" . counsel-recentf))
    :config
    (counsel-mode 1))
#+end_src

** Ivy-Rich
:PROPERTIES:
:ID:       B416C756-DC98-428A-BBCE-092A9D74C48F
:END:
   Ivy-rich enables prettifying the ivy output
#+begin_src emacs-lisp
  (use-package ivy-rich
    :diminish ivy-rich-mode
    :hook ((ivy-mode counsel-mode) . ivy-rich-mode)
    :custom
    (ivy-virtual-abbreviate 'abbreviate)
    (ivy-rich-path-style 'abbrev)
    :config
    (setcdr (assq t ivy-format-functions-alist) #'ivy-format-function-line))
#+end_src

** Swiper
:PROPERTIES:
:ID:       10CF374E-3325-40B2-84E1-1F5939D14B1F
:END:
   And finally, swiper for searching. I bind it to C-s so that I use it instead of i-search.

   I'm now binding swiper-thing-at-point to C-s since I'm usually searching for th thing I'm looking at.
#+begin_src emacs-lisp
  (use-package swiper
    :commands (swiper swiper-all)
    :bind ("C-s" . 'swiper-thing-at-point))
#+end_src

* Git stuff
:PROPERTIES:
:ID:       222C779E-4D0E-4A6D-86EF-BB2473091EDA
:END:
Magit is a great interface to git (although the [[https://magit.vc/manual/magit/][documentation]] is quite dense).
#+begin_src emacs-lisp
  (use-package magit
    :bind (("C-x g" . magit-status)
           ("C-x M-g" . magit-dispatch-popup)))
#+end_src
Apart from the keybindings, I don't need to make any config changes.

I like to have a visual git status in the gutter/fringe, for that I use [[https://github.com/emacsorphanage/git-gutter][git-gutter.el]]
#+begin_src emacs-lisp
  (use-package git-gutter
    :diminish git-gutter-mode
    :init
    (custom-set-variables
     '(git-gutter:update-interval 2))
    :config
    (global-git-gutter-mode +1))
#+end_src
Dimish the mode so that it doesn't clutter up our mode line/status bar.

The update-interval config is to enable live updating (every 2 seconds of idle time).

I enable it globally because I use git for many different files, not just code.

* Projectile
:PROPERTIES:
:ID:       62579B8F-D53C-4AD0-8B20-03728D55D5A8
:END:
[[https://github.com/bbatsov/projectile][Projectile]] is handy for interacting with projects, and it can integrate with Helm or Ivy nicely.
#+begin_src emacs-lisp
  (use-package projectile
    :demand
    :bind (:map projectile-mode-map
              ("C-c p" . projectile-command-map))
    :init
    (setq projectile-completion-system 'ivy)
    (setq projectile-enable-caching t)
    :config
    (add-to-list 'projectile-globally-ignored-files "node-modules")
    (projectile-mode))
#+end_src

And since I'm currently using Ivy & Counsel, I'll include the [[https://github.com/ericdanan/counsel-projectile][counsel-projectile]] integration too.

#+begin_src emacs-lisp
  (use-package counsel-projectile
    :diminish
    :demand
    :config
    (counsel-projectile-mode))
#+end_src

** TODO [[https://github.com/ericdanan/counsel-projectile#setting-counsel-projectile-org-capture-templates][counsel-projectile-org-capture]]

* Code/Text Completion (company-mode)
:PROPERTIES:
:ID:       F84430C0-7845-42EF-BC84-B890B6541319
:END:
Got to have those sweet code-completion popups, courtesy of [[https://company-mode.github.io/][company-mode]].
#+begin_src emacs-lisp
    (use-package company
      :diminish
      :bind (("C-." . #'company-complete))
      :custom
      (company-dabbrev-downcase nil "Don't downcase returned candidates.")
      (company-show-numbers t "Numbers are helpful.")
      (company-tooltip-limit 20 "The more the merrier.")
      (company-tooltip-idle-delay 0.4 "Faster!")
      (company-async-timeout 20 "Some requests can take a long time. That's fine.")
      :config
      ;; Use the numbers 0-9 to select company completion candidates
      (let ((map company-active-map))
        (mapc (lambda (x) (define-key map (format "%d" x)
                            `(lambda () (interactive) (company-complete-number ,x))))
              (number-sequence 0 9)))
      :init
      (setq company-tooltip-minimum-width 10)
      (global-company-mode))
#+end_src
I've had issues with company popups being ragged when I'm using a proportional font. So I'm using [[https://github.com/tumashu/company-posframe/][company-posframe]] to enable child frames instead.
#+begin_src emacs-lisp
  (use-package company-posframe
    :init
    (company-posframe-mode 1))
#+end_src

* Parentheses
:PROPERTIES:
:ID:       EA3A7F78-4582-44A8-B337-D26634F90745
:END:
I find it invaluable to have parentheses matching enabled.
#+begin_src emacs-lisp
  (show-paren-mode t)
#+end_src
And I like the visual delimitation of colour. Rainbow-delimiters adds that.
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :diminish
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

* Line numbers
:PROPERTIES:
:ID:       C3251E38-D78C-4974-97BB-D56BF7C1FB43
:END:
I want line numbers on all code editing buffers. Since they should all
derive from prog-mode, I'll set line numbers there and hope for the
best. The alternative is to enable global line numbers then turn it
off in other modes, but that seems messier to me.
#+begin_src emacs-lisp
(add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+end_src

* Development languages
  I'm going to try lsp-mode again, for languages it supports.

  Emacs 27 with lsp-mode is super fast and really good to use.

  Here's the core lsp-configuration:
#+begin_src emacs-lisp :tangle no
  (use-package lsp-mode
    :hook (
           ;; bind lsp to the development modes I'm interested in.
           (web-mode . lsp-deferred)
           (yaml-mode . lsp-deferred)
           (java-mode . lsp-deferred)
           (lsp-mode . lsp-enable-which-key-integration))
    :init
    (setq lsp-keymap-prefix "C-l")
    (setq lsp-enable-completion-at-point t)
    (setq lsp-enable-indentation t)
    (setq lsp-enable-on-type-formatting t)
    (setq gc-cons-threshold 100000000)
    (setq read-process-output-max (* 1024 1024)) ;; 1mb
    :commands lsp lsp-deferred)

  (use-package lsp-ui)
#+end_src
I've changed the default prefix from "s-l" to "C-l".

According to the [[https://emacs-lsp.github.io/lsp-mode/page/performance/][lsp-mode documentation]], a few things should be tweaked for maximum performance.

The default setting is too low for lsp-mode's needs due to the fact that client/server communication generates a lot of memory/garbage. I've taken the easy approach of just setting this to 100mb in the lsp-mode init section above.
#+begin_src emacs-lisp :tangle no
(setq gc-cons-threshold 100000000)
#+end_src

Similarly the the amount of data which Emacs reads from the process needs increasing. The emacs default (4k) is too low considering that some of the language server responses are in 800k - 3M range.

#+begin_src emacs-lisp :tangle no
(setq read-process-output-max (* 1024 1024)) ;; 1mb
#+end_src

Turn on ivy integration for lsp:
#+begin_src emacs-lisp :tangle no
    (use-package lsp-ivy
      :after (ivy lsp-mode)
      :commands lsp-ivy-workspace-symbol)
#+end_src

** Treemacs
:PROPERTIES:
:ID:       10C03793-2F9A-459E-A271-83814F642CE3
:END:

   Sometimes I want an IDE style tree view, so lets enable treemacs and lsp-treemacs
   This doesn't work with eglot, so it's disabled for now.
#+begin_src emacs-lisp :tangle no
  (use-package lsp-treemacs
    :custom
    (lsp-treemacs-sync-mode 1)
    :after (eglot))
#+end_src

Treemacs provides a very configurable tree-view. I'm going to see how I get on with it, so I've just grabbed a basic config from the [[https://github.com/Alexander-Miller/treemacs][treemacs documentation]].

C-x t t should toggle the treeview, and I'll see how I get on with that.

#+begin_src emacs-lisp
  (use-package treemacs
    :ensure t
    :defer t
    :init
    (with-eval-after-load 'winum
      (define-key winum-keymap (kbd "M-0") #'treemacs-select-window))
    :config
    (progn
      ;; The default width and height of the icons is 22 pixels. If you are
      ;; using a Hi-DPI display, uncomment this to double the icon size.
      ;;(treemacs-resize-icons 44)

      (treemacs-display-current-project-exclusively) ;; don't show other projects, just what I'm working on now.
      (treemacs-project-follow-mode t) ;; automatically switch to the project for the current buffer
      (treemacs-tag-follow-mode t)
      (treemacs-filewatch-mode t)
      (treemacs-fringe-indicator-mode 'always)
      (treemacs-git-mode 'simple))
    :bind
    (:map global-map
          ("M-0"       . treemacs-select-window)
          ("C-x t 1"   . treemacs-delete-other-windows)
          ("C-x t t"   . treemacs)
          ("C-x t B"   . treemacs-bookmark)
          ("C-x t C-t" . treemacs-find-file)
          ("C-x t M-t" . treemacs-find-tag)))
#+end_src

And since we're also using projectile, let's enable treemacs integration
#+begin_src emacs-lisp
  (use-package treemacs-projectile
    :after (treemacs projectile)
    :ensure t)
#+end_src

Make things pretty with all-the-icons
#+begin_src emacs-lisp
  (use-package treemacs-all-the-icons
    :after (treemacs))
#+end_src

** Javascript/web development (lsp?)
:PROPERTIES:
:ID:       076E4BC3-4249-4D42-8189-07AE65146B45
:END:
   There are several ways to configure javascript & typescript support. I'm going with web-mode since it can handle template-based development (react, vue etc.) along with raw js & ts files.

#+begin_src emacs-lisp
  (use-package web-mode
    :ensure t
    :mode (("\\.js\\'" . web-mode)
           ("\\.jsx\\'" . web-mode)
           ("\\.ts\\'" . web-mode)
           ("\\.tsx\\'" . web-mode)
           ("\\.html\\'" . web-mode)
           ("\\.vue\\'" . web-mode)
           ("\\.json\\'" . web-mode))
    :commands web-mode
    :config
    (setq company-tooltip-align-annotations t)
    (setq web-mode-markup-indent-offset 2)
    (setq web-mode-css-indent-offset 2)
    (setq web-mode-code-indent-offset 2)
    (setq web-mode-enable-part-face t)
    (setq web-mode-content-types-alist
          '(("jsx" . "\\.js[x]?\\'")))
    )
#+end_src

You will need to install the [[https://github.com/sourcegraph/javascript-typescript-langserver][javascript-typescript-langserver]] for lsp to work with javascript.
#+begin_src sh :tangle no
npm i -g javascript-typescript-langserver
#+end_src

Alternatively, this could be installed as a docker container, and then you could avoid installing npm/node on your local machine. I'll have to give that another go sometime.

** Java

*** lsp-mode (Deprecated)
   Setup lsp-java
   #+begin_src emacs-lisp :tangle no
     (use-package lsp-java
      :hook (java-mode . lsp)
      :bind (:map java-mode-map
                  ([tab] . company-indent-or-complete-common)))
   #+end_src

   Also configure dap-mode for debugging.
   #+begin_src emacs-lisp :tangle no
     (use-package dap-mode
       :after lsp-mode

       :config (dap-auto-configure-mode)
       (add-hook 'dap-stopped-hook
                 (lambda (arg) (call-interactively #'dap-hydra))))

     (use-package dap-java
       :ensure nil)
   #+end_src

*** eglot
:PROPERTIES:
:ID:       E0EF0257-1A62-4B0B-BD11-C7E0899FD5D6
:END:

Setup eglot-java
#+begin_src emacs-lisp
  (use-package eglot-java
    :hook (
           (java-ts-mode . eglot-java-mode)
           (java-mode . eglot-java-mode))
    :bind (:map eglot-java-mode-map
                ("C-c <tab>" . company-complete)
                ("C-c l n" . eglot-java-file-new)
                ("C-c l x" . eglot-java-run-main)
                ("C-c l t" . eglot-java-run-test)
                ("C-c l N" . eglot-java-project-new)
                ("C-c l T" . eglot-java-project-build-task)
                ("C-c l R" . eglot-java-project-build-refresh))
    ;;:custom
    ;;(eglot-java-java-home '("/Users/giles.paterson/.jenv/versions/21"))
    ;;(eglot-java-java-program '("/Users/giles.paterson/.jenv/versions/21/bin/java"))
    )
  #+end_src
    When doing maven builds etc, it's nice to have the compilation buffer autoscroll:
  #+begin_src emacs-lisp
    (setq compilation-scroll-output t)
   #+end_src

*** tree-sitter
#+begin_src elisp :tangle no
   (use-package tree-sitter
     :ensure t
     :config
     (global-tree-sitter-mode)
     (require 'tree-sitter-langs))

   (use-package tree-sitter-langs
     :ensure t)
   #+end_src

*** Cucumber tests
:PROPERTIES:
:ID:       04F81AC6-4A47-4E99-8E16-D6CAC6CD3AE0
:END:
#+begin_src emacs-lisp
  (use-package feature-mode
    :mode (("\\.feature\\'" . feature-mode)))
#+end_src
** Rust
:PROPERTIES:
:ID:       9654D859-5BB6-4591-9BDB-D55264B28A7B
:END:
Setup rust-mode and lsp for Rust programming

For this to work, you need rust-analyzer installed. The easiest method is to use rustup:
#+begin_src sh :tangle no
  rustup component add rust-analyzer
#+end_src

#+begin_src emacs-lisp
  (use-package rust-mode
    :ensure t
    :mode (("\\.rs\\'" . rust-mode))
    :init
    (which-function-mode 1)
    :config
    (setq rust-format-on-save t))

#+end_src

* Yaml
:PROPERTIES:
:ID:       9F7C56E9-72B2-4E43-AFF4-D6932C1782BA
:END:
#+begin_src emacs-lisp
  (use-package yaml-mode
    :ensure t
    :mode ("\\.ya?ml\\'" . yaml-mode))
#+end_src

* Restclient
:PROPERTIES:
:ID:       8EDC12C4-1DBB-45CA-AAB4-9CEADE95D7EA
:END:
[[https://github.com/pashky/restclient.el][A tool for interacting with webservices.]]
[[https://erick.navarro.io/blog/testing-an-api-with-emacs-and-restclient/][This]] is a good intro to using restclient.
Bind it to .http files.
#+begin_src emacs-lisp
  (use-package restclient
    :ensure t
    :mode ("\\.http\\'" . restclient-mode))
#+end_src

We can enable completion for it via company mode
#+begin_src emacs-lisp
  (use-package company-restclient
    :ensure t
    :after (company restclient)
    :hook ((restclient-mode-hook . (lambda() (setq company-backend (company-restclient))))))
#+end_src

And, of course, we can integrate it with org mode:
#+begin_src emacs-lisp
  (use-package ob-restclient
     :ensure t
     :defer t
     :after org restclient)
#+end_src

* uLisp
:PROPERTIES:
:ID:       7E0C6607-B068-4741-ABC8-24B1B8351735
:END:



    I've installed [[http://www.ulisp.com/show?3KN3][uLisp]] on a Raspberry Pi Pico, and it should be possible to use inferior lisp mode to interact with it.


 #+begin_src emacs-lisp
   (defvar port "/dev/ttyACM1" "rasoberry-pi-pico")
   (defvar bauds 9600 "Bps")
   (defun sb-open()
     (let ((serial-buffer (serial-term port bauds)))
       (with-current-buffer
           (rename-buffer "*inferior-lisp*")
         (term-line-mode)
         (setq inferior-lisp-buffer serial-buffer))))
  #+end_src

* Remote access with Tramp
:PROPERTIES:
:ID:       2EC4CD3E-8FBE-4CB9-BC3C-9228541452B8
:END:
  Tramp is an emacs feature that lets you edit a file on a remote machine via ssh and other methods. I only really want ssh, so I'll set that as the default

#+begin_src emacs-lisp
  (setq tramp-default-method "ssh")
#+end_src

* Structurizr Mode
:PROPERTIES:
:ID:       DF45EDFE-E229-440D-8798-9C77685B7ADD
:END:
This is my custom structurizr mode (available on github at https://github.com/gilesp/structurizr-mode).

#+begin_src emacs-lisp
  `((user :default ,user-login-name))
  (use-package structurizr-mode
    :ensure nil
    :load-path "~/projects/structurizr-mode"
    :mode ("\\.dsl\\'" . structurizr-mode))
#+end_src

* SQL Mode (Disabled)

Use ob-sql-mode to enable sql mode in org files

  #+begin_src emacs-lisp :tangle no
    (use-package ob-sql-mode
      :ensure t)
#+end_src

And set up some sql-mode connections
#+begin_src emacs-lisp :tangle no
  (setq sql-connection-alist
        '((productinfo-test (sql-product 'oracle)
                            (sql-server "oracle-productinfodb-test.service.test.fruugo")
                            (sql-user "productinfo")
                            (sql-password "productinfo")
                            (sql-database "orcl"))))
#+end_src

* LLM assistant

** Local LLMs [Disabled]
I've started using ollama at work to run a number of code oriented LLMs on a beefy AI server. It'd be good to access these from within Emacs as well as via IntelliJ and the web as we currently do.

+I'm going to try the [[https://github.com/s-kostyaev/ellama][ellama]] project to interract with our ollama instances.+

#+begin_src emacs-lisp :tangle no
  (use-package ellama
    :bind ("C-c e" . ellama-transient-main-menu)
    :init
    (setopt ellama-language "English")
    (require 'llm-ollama)
    (setopt ellama-provider
            (make-llm-ollama
             :host "hdc-m37-llm-01.service.test.fruugo"
             :port 11434
             :chat-model "qwen2.5-coder:7b"
             :embedding-model "qwen2.5-coder:7b"))
    (setopt ellama-coding-provider
            (make-llm-ollama
             :host "hdc-m37-llm-01.service.test.fruugo"
             :port 11437
             :chat-model "codegeex4"
             :embedding-model "codegeex4"))
    ;; Naming new sessions with llm
    (setopt ellama-naming-provider
           (make-llm-ollama
             :host "hdc-m37-llm-01.service.test.fruugo"
             :port 11434
             :chat-model "qwen2.5-coder:7b"
             :embedding-model "qwen2.5-coder:7b"
             :default-chat-non-standard-params '(("stop" . ("\n")))))
    (setopt ellama-naming-scheme 'ellama-generate-name-by-llm)

    )
#+end_src

** GPTEL [Disabled]

Pausing my use of gptelk to experiment with Editor Code Assistant

+I'm going to try [[https://github.com/karthink/gptel][gptel]] now, since we've switched to the cloud versions of claude, chatgpt and claude instead of our local llms.+

#+begin_src emacs-lisp :tangle no
  (use-package gptel
    :bind (("C-c g" . gptel-send))
    :init
    (gptel-make-gemini "Gemini"
      :key (gptel-api-key-from-auth-source "generativelanguage.googleapis.com")
      :request-params '(:tools [(:google_search ())]
                               :generationConfig (:thinkingConfig (:includeThoughts "false")))
      :stream t)
    :config
    (require 'gptel-integrations))
#+end_src

gptel will read keys from [[https://github.com/karthink/gptel?tab=readme-ov-file#optional-securing-api-keys-with-authinfo][~/.authinfo]], so I'll set my keys there.
ChatGPT is configured by default, but you need to enable other backends individually.

** Editor Code Assistant
:PROPERTIES:
:ID:       46F92344-22DA-4C49-916D-7DCCCC0C6A5A
:END:

#+begin_src emacs-lisp
;; An interrupted :vc clone leaves an empty elpa/eca dir behind, which makes
;; package-vc-install prompt "Overwrite previous checkout?" on every startup
;; and block init until answered. Clear it out first so that can't happen.
(let ((eca-dir (expand-file-name "elpa/eca" user-emacs-directory)))
  (when (and (file-directory-p eca-dir)
             (null (directory-files eca-dir nil directory-files-no-dot-files-regexp)))
    (delete-directory eca-dir)))

(use-package eca
  :vc (:url "https://github.com/editor-code-assistant/eca-emacs" :rev :newest))
#+end_src

** MCP usage [Disabled]
I've not made much use of the mcp servers, and found that they were just sitting idle most of the time.
+Lets configure some Model Context Protocol servers to augment gptel+

#+begin_src emacs-lisp :tangle no
    (use-package mcp
    :ensure t
    :after gptel
    :custom (mcp-hub-servers
             `(("filesystem" . (:command "npx" :args ("-y" "@modelcontextprotocol/server-filesystem" "/Users/giles.paterson/")))
               ("jira" . (:command "docker"
                          :args ("run" "-i" "--rm"
                                 "-e" "CONFLUENCE_URL"
                                 "-e" "CONFLUENCE_USERNAME"
                                 "-e" "CONFLUENCE_API_TOKEN"
                                 "-e" "JIRA_URL"
                                 "-e" "JIRA_USERNAME"
                                 "-e" "JIRA_API_TOKEN"
                                 "ghcr.io/sooperset/mcp-atlassian")
                          :env (:CONFLUENCE_URL "https://fruugo-com.atlassian.net/wiki"
                                :CONFLUENCE_USERNAME "giles.paterson@fruugo.com"
                                :CONFLUENCE_API_TOKEN "***REMOVED-REVOKED-TOKEN***"
                                :JIRA_URL "https://fruugo-com.atlassian.net/"
                                :JIRA_USERNAME "giles.paterson@fruugo.com"
                                :JIRA_API_TOKEN "***REMOVED-REVOKED-TOKEN***")))
               ("fruugo" . (:url "http://localhost:8080/sse" )))
  )
    :config (require 'mcp-hub)
    :hook (after-init . mcp-hub-start-all-server))
#+end_src

* Scheme
:PROPERTIES:
:ID:       6085AFD0-ADBB-4790-8707-765A8A11E472
:END:
Let's give scheme a go, while I work my way through "The Little Schemer".

I'm going to try Guile and geiser.

#+begin_src emacs-lisp
  (use-package geiser-guile
    :ensure t)
#+end_src

#+RESULTS:
